server:
  #端口号
  port: 8080
  #项目名，如果不设定，默认是 /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java-user?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: java
    password: LimYoonA90
    driver-class-name: com.mysql.cj.jdbc.Driver
    setAllowPublicKeyRetrieval: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: # 如果未单独配置默认为空即可
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

mybatis-plus:
  mapper-locations:
    - classpath:/mybatis/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl